### ISSUE TITLE
connection refused

### ISSUE THREAD

**Issue by life-on-mars** [Nezrahm/bitburner-sync#1]
I'm getting connection refused errors no matter what I try. Tried to restart steam client, enable API autostart etc. to no avail. 
Node.js v17.9.0

```
11:18:53 - Found 0 files to sync
node:events:505
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED ::1:9990
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1195:16)
Emitted 'error' event on ClientRequest instance at:
    at Socket.socketErrorListener (node:_http_client:454:9)
    at Socket.emit (node:events:527:28)
    at emitErrorNT (node:internal/streams/destroy:164:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -4078,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '::1',
  port: 9990
}
```

**Comment by Nezrahm** [comment]
Which versions of Bitburner and bitburner-sync are you using?
Which OS are you using?
Is the bitburner-sync and bitburner installation on the same, logical, machine?
The sync is currently hardcoded to only work for localhost.

**Comment by life-on-mars** [comment]
same machine
Windows 11
sync 1.2
bitburner 1.6.4

**Comment by Nezrahm** [comment]
Ok, that should work fine, you are not playing around with WSL on Windows?

I get a very similar error if the API server is disabled.

> npx bitburner-sync
> 5:18:33 PM - Found 49 files to sync
> node:events:498
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: connect ECONNREFUSED 127.0.0.1:9990
>     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16)
> Emitted 'error' event on ClientRequest instance at:
>     at Socket.socketErrorListener (node:_http_client:442:9)
>     at Socket.emit (node:events:520:28)
>     at emitErrorNT (node:internal/streams/destroy:157:8)
>     at emitErrorCloseNT (node:internal/streams/destroy:122:3)
>     at processTicksAndRejections (node:internal/process/task_queues:83:21) {
>   errno: -61,
>   code: 'ECONNREFUSED',
>   syscall: 'connect',
>   address: '127.0.0.1',
>   port: 9990
> }

Can you double check that the API server truly is enabled?

![image](https://user-images.githubusercontent.com/8653358/166483708-2abb5fb5-70b7-414b-af2a-f7a1a6622695.png)

If it is enabled then would I suggest looking at things like Windows Firewall or similar (any antivirus?). They shouldn't cause any issue though since they seldom block localhost.

If you want to then can you contact me at the Bitburner discord to try and figure this out.

**Comment by life-on-mars** [comment]
I've tried all combinations in that API menu.
Additionally, I've just tested taking a browser to http://localhost:9990 and I get a response, so the API server seems to be working and is accessible.

I've tried running the node.js window as Admin... that didn't work.
Node.js was installed using chocolatey btw, if that info is of any use.

**Comment by life-on-mars** [comment]
> Ok, that should work fine, you are not playing around with WSL on Windows?

What do you mean by that? I do have WSL installed but it's nothing fancy.

**Comment by Nezrahm** [comment]
If you are just browsing to that port then should you be greeted with

> {"success":false,"msg":"Invalid authentication token"}

Is that happening?

By "node.js window", are you referring to a PowerShell terminal or what?

Installing via choco is very rarely a bad thing. Should work just fine.

Are you running the bitburner-sync via WSL? The WSL is running via a virtual network and cannot be considered the same logical machine as base Windows.

**Comment by Nezrahm** [comment]
And you shouldn't need any admin privileges for running the sync.

**Comment by life-on-mars** [comment]
"node.js command prompt" from the start menu... but in cmd.exe it's the same

admin mode... well... windows mantra... in Linux I would simply consult the logs or RTFM... in Windows even a cup of n00dles won't help

yes... that's the message I got through the browser

and no... I wasn't using WSL to run bitburner-sync... but after you mentioned it... you know I did what I was told not to and tried anyway... couldn't even get npm running in WSL ^_^

**Comment by life-on-mars** [comment]
sorted out in discord chat... just in case anyone else is having this problem:

bitburner-sync tried to access localhost through ipv6 while the API server apparently was only listening on ipv4
this presumably occurs on Windows 11 only
as a workaround change "localhost" in _\node_modules\bitburner-sync\src\client.js_ to "127.0.0.1"
