### ISSUE TITLE
save scripts

### ISSUE THREAD

**Issue by BotTheLostOne** [Nezrahm/bitburner-sync#3]
is there anyway to select where to save scripts

**Comment by Ongest** [comment]
found a solution

**Comment by Nezrahm** [comment]
You might have to clarify your question.

The parameter "scriptRoot" controls where files are read from or stored. You are talking about saving scripts so I assume you are doing a "get"?

Or do you want to control where in bitburner there files are stored? Like on which server? The API only allows to access files on the "home" server.

**Comment by BotTheLostOne** [comment]
I managed to make it work, I use /Scripts as the location and it worked reading but saving either gave a error or save in the install folder but thank you it is a amazing tool

**Comment by Nezrahm** [comment]
What error did you get? And what did you do to fix it?
It would be nice to know, either so others can learn from it or if it's something I can fix/change with the tool.

**Comment by BotTheLostOne** [comment]
got \Scripts' is not a directory, and to fix it I remove the \ so just used just Scripts and it worked,

**Comment by Nezrahm** [comment]
Right, so what happened there is that you gave a fully qualified path ("/Scripts") so the system is looking for a Scripts directory in your root folder (Unix style folder, for Windows it would be like "C:\Scripts").

If you either remove the first slash or give a "." first then the path is interpreted as a relative path, which is what you wanted in this case. So "./Scripts" or just "Scripts" should both work fine.
